<?php /** @var Digia\AvardaCheckout\Block\Checkout $block */ ?>
<?php
  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $getLocale = $objectManager->get('Magento\Framework\Locale\Resolver');
  $config = [
    "baseMediaUrl" => $block->getBaseMediaUrl(),
    "baseUrl" => $block->getBaseUrl(),
    "countryId" => $block->getCountryId(),
    "customerId" => $block->getCustomerId(),
    "hasItems" => $block->hasItems(),
    "magentoLocale" => $getLocale->getLocale(),
    "maskedQuoteId" => $block->getMaskedQuoteId(),
    "quoteId" => $block->getQuoteId(),
    "saveOrderUrl" => $block->getSaveOrderUrl(),
    "callbackUrl" => $block->getCallbackUrl()
  ];
?>

<div id="checkout-root"></div>
<script>
window.checkoutConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
// Create aliases for customer.js model from customer module
window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
window.customerData = window.checkoutConfig.customerData;
</script>
<script type="text/javascript">
require.config(({
  shim: {
    AvardaCheckOutClient: {
      exports: 'AvardaCheckOutClient'
    }
  },
  paths: {
    AvardaCheckOutClient:<?php echo json_encode($block->getCheckOutClientScriptPath()); ?>
  }
}));
require([
  'avardaCheckout',
  //'Markup_Smartship/js/view/checkout/shipping/additional-block'
], function(avardaCheckout, /*Smartship*/) {
  avardaCheckout.execute(
    <?php echo json_encode($config); ?>,
    {
      //shippingAdditional: Smartship
    }
  );
});
</script>
