<?php $purchaseId = $this->getPurchaseId(); ?>
<a href="<?= $this->getSaveOrderUrl() . 'purchase/' . $purchaseId; ?>">
    <?= __("If you don't get redirected in 5 seconds, click this link to continue."); ?>
</a>
<div id="checkOutDiv"></div>
<script src="<?= $this->getCheckOutClientScriptPath(); ?>.js"></script>
<script>
  var options = {
    divId: "checkOutDiv",
    purchaseId: "<?= $purchaseId; ?>",
    done: function (purchaseId) {
      window.location.href = "<?= $this->getSaveOrderUrl(); ?>purchase/" + purchaseId;
    }
  };
  AvardaCheckOutClient.init(options);
</script>
