<?php $purchaseId = $this->getPurchaseId(); ?>
<a href="<?= $this->getSaveOrderUrl() . '/purchase/' + $purchaseId; ?>">Process Order</a>
<div id="checkOutDiv"></div>
<script src="<?= $this->getCheckOutClientScriptPath(); ?>.js"></script>
<script>
  var options = {
    // ID of the <div> inside which to render the form
    divId: "checkOutDiv",

    purchaseId: "<?= $purchaseId; ?>",

    // What to do once the result is available
    done: function (purchaseId) {
      window.location.href = "<?= $this->getSaveOrderUrl(); ?>/purchase/" + purchaseId;
    }
  };
  AvardaCheckOutClient.init(options);
</script>
