<?php /** @var Digia\AvardaCheckout\Block\Checkout $block */ ?>
<?php
  $devMode = $block->getIsDevMode();
?>

<div id="checkout-root"></div>

<script type="text/javascript">
console.log('Hello from config!');
// TODO: Inject all the required configs here
</script>

<?php if($devMode) : ?>
  <script type="text/javascript" src="http://avarda.box:8080/assets/bundle.js"></script>
<?php else : ?>
  <script type="text/javascript" src="<?php echo $block->getViewFileUrl('Digia_AvardaCheckout::js/bundle.js');?>"></script>
<?php endif ?>
