<?php /** @var Digia\AvardaCheckout\Block\Checkout $block */ ?>
<?php
  $devMode = $block->getIsDevMode();
  $config = [
    "baseUrl" => $block->getBaseUrl(),
    "baseMediaUrl" => $block->getBaseMediaUrl(),
    "maskedQuoteId" => $block->getMaskedQuoteId(),
  ];
  //$config->baseUrl = $block->getBaseUrl();
  //$config->baseMediaUrl = $block->getBaseMediaUrl();
  // echo $block->foobar();
?>

<div id="checkout-root"></div>
<?php echo __('Checkout'); ?>

<script type="text/javascript">
console.log('Hello from config!');
window.__avarda_checkout_config__ = <?php echo json_encode($config); ?>;
</script>


<?php if($devMode) : ?>
  <script type="text/javascript" src="http://avarda.box:8080/assets/bundle.js">
  </script>
<?php else : ?>
  <script type="text/javascript" src="<?php echo $block->getViewFileUrl('Digia_AvardaCheckout::js/bundle.js');?>"></script>
<?php endif ?>
 <script type="text/javascript">
 avardaCheckout.execute(/*
   TODO: Re-enable this!
   require('mage/translate')
 */);
 </script>
