// flow-typed signature: 61404f4724694c64bfcd49834a8e2455
// flow-typed version: <<STUB>>/@mapbox/sanitize-caja_v^0.1.4/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@mapbox/sanitize-caja'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@mapbox/sanitize-caja' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@mapbox/sanitize-caja/sanitizer-bundle' {
  declare module.exports: any;
}

declare module '@mapbox/sanitize-caja/test/sanitize' {
  declare module.exports: any;
}

// Filename aliases
declare module '@mapbox/sanitize-caja/index' {
  declare module.exports: $Exports<'@mapbox/sanitize-caja'>;
}
declare module '@mapbox/sanitize-caja/index.js' {
  declare module.exports: $Exports<'@mapbox/sanitize-caja'>;
}
declare module '@mapbox/sanitize-caja/sanitizer-bundle.js' {
  declare module.exports: $Exports<'@mapbox/sanitize-caja/sanitizer-bundle'>;
}
declare module '@mapbox/sanitize-caja/test/sanitize.js' {
  declare module.exports: $Exports<'@mapbox/sanitize-caja/test/sanitize'>;
}
