// flow-typed signature: b8f04b9557d825f617967ef5235c0fde
// flow-typed version: <<STUB>>/babel-preset-minify_v^0.2.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-minify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-minify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-minify/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-minify/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-minify/lib/index'>;
}
